### ISSUE TITLE
plugin doesn't use the same serenity.properties depending of where maven start

### ISSUE THREAD

**Issue by dwursteisen** [serenity-bdd/serenity-maven-plugin#22] opened 2016-01-13 14:48 UTC
To reproduce the problem : 

- `git clone` https://github.com/dwursteisen/serenity-bug-report/tree/submodule (use the branch submodule)
- `mvn clean install` from the root directory : no report/wrong report generated in `target/site/serenity`
- `mvn clean install` from the module directory : a report is generated in `module\target\site\serenity`

expected result : `mvn clean install` from the root directory produce the same result as  `mvn clean install` from the module directory. Both command should generate a report in `module\target\site\serenity`

**Comment by wakaleo** [comment] 2016-01-13 14:53
This is quite hard because Maven. The serenity.outputDirectory provides some workarounds but is not ideal.

**Comment by dwursteisen** [comment] 2016-01-14 16:29
you mean the `serenity.outputDirectory` in the `<configuration>` part of the maven plugins ? 

But I can't configure everything using only the plugins;

- `serenity.test.root`
- `feature.file.encoding`
- `serenity.report.encoding`
- `serenity.project.name`
- `serenity.requirement.types`

(To be honest, I'm not sure that I fully understood your answer :P, so sorry if my answer seems to be out of the point )

**Comment by YamStranger** [comment] 2016-01-14 18:49
Hello @dwursteisen. 

I think @wakaleo mean possibility set output directory for serenity reports. For example, if you have sub module build, and want have reports under "root project" you can specify two serenity.properties files:

1) In root project (with parent pom) - serenity.properties file with the following line:
```serenity.outputDirectory= aggregate_report```
2) in module with serenity tests (child pom) different serenity.properties file with value:
``` serenity.outputDirectory=../aggregate_report ```

As result you will receive report in one place, but as sad @wakaleo it is not ideal solution, and now I am looking for some best approach with your example.

**Comment by YamStranger** [comment] 2016-01-29 08:07
Hello @dwursteisen 

Please check it, now it should work fine with serentiy-maven-plugin:1.1.25-rc.3 and serenity-core with serenity-core:1.1.25-rc.3. 
Now, if you will have some project with multi module structure, for example:
App
\- bdd
\- core
\- bdd2

during ``` maven clean verify ``` sererenity.properties from module directory will override properties from project directory (serenity.properties from bdd will override properties in App dir if they are exists), and by default output directory of reports is in module directory, and path provided relative to module directory. 

So after build, by default reports will be under: 
```
App/
  bdd/
     target/serenity/site
  core/
     target/serenity/site
  bdd2/
     target/serenity/site
```

Please check this fix, and if all works fine - please close this issue. 

Thanks a lot!!!

**Comment by dwursteisen** [comment] 2016-01-30 07:58
Thanks for update.

I will look at it the next week.

Regards.

**Comment by dwursteisen** [comment] 2016-02-03 15:38
The aggregation seems working. __but__ the result still is not the same.

If your using my test project, the feature panel is not here if you build the root project. But is here if you build the module project.

The I still should run `serenity:aggregate` on the correct module

**Comment by YamStranger** [comment] 2016-02-03 15:44
Hello @dwursteisen. Will check feature panel with your project. 

Thanks!

**Comment by YamStranger** [comment] 2016-02-09 10:40
Hello @dwursteisen I updated you project (this [pull request](https://github.com/dwursteisen/serenity-bug-report/pull/1))

So, now I see what you mean - If ```mvn clean verify``` run from module then: 
![bug_module1](https://cloud.githubusercontent.com/assets/1667699/12913806/888523f8-cf29-11e5-821e-c93418291e4c.png)
![bug_module2](https://cloud.githubusercontent.com/assets/1667699/12913805/8883a2bc-cf29-11e5-985d-e1c4e3d856b7.png)

and if from project dir then: 

![bug_root1](https://cloud.githubusercontent.com/assets/1667699/12913820/992d9938-cf29-11e5-82cd-7e088d82570f.png)
![bug_root2](https://cloud.githubusercontent.com/assets/1667699/12913819/99239a64-cf29-11e5-968c-c015f8fb6672.png)

**Comment by YamStranger** [comment] 2016-02-10 10:02
Depends on serenity-bdd/serenity-core/issues/305

**Comment by YamStranger** [comment] 2016-02-10 14:14
Hello @dwursteisen 

This issue fixed and you can check it with next serenity-core and serenity-maven-plugin release.  Now report for you project contains what you want 
![issue_fix](https://cloud.githubusercontent.com/assets/1667699/12949577/4fd2d1a2-d011-11e5-81b3-83d1cf4dbde7.png)

**Comment by dwursteisen** [comment] 2016-02-17 16:58
Hello, 

I try your fix today. It's better _but_ we still have some issues :P

If I add several features in other directories, if I run `mvn clean install` from the root directory, I got this following result (click on Requirements)

_please note that I updated the sample project__

![img](https://raw.githubusercontent.com/dwursteisen/serenity-bug-report/submodule/bug1.PNG)

If I run from the module directory, I got this result : 

![img](https://raw.githubusercontent.com/dwursteisen/serenity-bug-report/submodule/bug2.PNG)

The funny thing is : 

1. the result is not always the same if I run `mvn clean install` from the root 
1. in fact, there is no pending test : all tests should be OK !
1. the result is not the same if the feature name match the feature name file. (ie: aa.feature is for feature named aa, but if the feature, in aa.feature, is named "oh no" it shouldn't work). _it may a cucumber issue_

**Comment by YamStranger** [comment] 2016-02-17 17:54
Thanks @dwursteisen

**Comment by YamStranger** [comment] 2016-02-20 07:15
Hello @dwursteisen 

For all works fine and as expected (same result in different dirs), so I can reproduce your "incorrect" report at all ( 

please try to follow next instructions: 

I run next 2 set of commands on two different PC with linux and included here result: 

```
git clone git@github.com:dwursteisen/serenity-bug-report.git
cd serenity-bug-report/
git checkout submodule
mvn clean install
firefox module/target/site/serenity/index.html
```
![bug1](https://cloud.githubusercontent.com/assets/1667699/13195110/11cf5e5e-d7b2-11e5-8c6a-dfc2039bd486.png)

and next: 
```
cd module/
```
![bug2](https://cloud.githubusercontent.com/assets/1667699/13195111/136fa994-d7b2-11e5-8fd1-75d516eb57ef.png)

Also I tried update your project to use latest version of serenity cucumber - and same result.  Maven version:
```
 mvn -version
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T22:10:27+02:00)
Maven home: /home/yamstranger/dev/apps/mvn/apache-maven-3.3.1
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /home/yamstranger/dev/apps/java/jdk1.8.0_65/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.2.0-16-generic", arch: "amd64", family: "unix"
```

Thanks!!!

**Comment by dwursteisen** [comment] 2016-02-20 07:23
I'm reproduce it under windows. I may check again next week.

The thing that I don't understand is that why I got a pending test. This
test is a copy of others test. But with a different name. Strange isn't it ?

Le sam. 20 févr. 2016 08:15, Yaroslav Pishta <notifications@github.com> a
écrit :

**Comment by YamStranger** [comment] 2016-02-20 07:30
@dwursteisen about this:
>The thing that I don't understand is that why I got a pending test. This test is a copy of others test. But with a different name. Strange isn't it ?

If it is wrong - it will be another issue, and under serentiy-cucumber module ) 

-- 

>I'm reproduce it under windows.

Hm, it quite strange ) Please try to follow provided steps, and if something will wrong I will try configure such build on windows. (I think that mvn may did not clean something... )

Thanks!!!!

**Comment by dwursteisen** [comment] 2016-02-20 09:00
> If it is wrong - it will be another issue, and under serentiy-cucumber
module

ok thanks, I will fill an issue next week

> Hm, it quite strange ) Please try to follow provided steps, and if
something will wrong I will try configure such build on windows. (I think
that mvn may did not clean something... )

you're right; I will try again, just to be shure.

Thanks !

Le sam. 20 févr. 2016 à 08:30, Yaroslav Pishta <notifications@github.com> a
écrit :

**Comment by YamStranger** [comment] 2016-02-25 14:02
Hello @dwursteisen, thanks for this notes, they were very useful during investigating if some issue can be reproduced on different PC:
>the result is not always the same if I run mvn clean install from the root 

This bug **can** appear only **for very fast** tests, almost **empty tests** (that take less than 1 seconds, as for my PC). If should be fixed under serenity-bdd/serenity-core/issues/322, and some little fixes will be included under serenity-bdd/serenity-jbehave/issues/45

Have you a change to check current issue? 
If you feel that it was fixed - please close this ticket. 

Thanks a lot!!!

**Comment by YamStranger** [comment] 2016-02-29 11:23
It seems that this issue already fixed and this ticket can be closed.

**Closed by YamStranger** 2016-02-29 11:23 UTC
Labels: bug, in progress
