### ISSUE TITLE
plugin resolving relative output and source directory to wrong path

### ISSUE THREAD

**Issue by Cristi003** [serenity-bdd/serenity-maven-plugin#9] opened 2015-07-10 18:43 UTC
The plugin is resolving the relative output and source directory to wrong path when running mvn outside the maven module and using thucydides prefix for the properties or the properties are missing
#### Example1(specifying output directory with thucyidides prefix):
current working directory = `a/b/c/`
mvn **-f path/to/module/pom.xml** clean verify site -Dthucydides.outputDirectory=/target/site/thucydides
serenity runner writes test outcomes to directory:
`/a/b/c/path/to/module/target/site/thucydidies`
plugin looks for test outcomes in directory:
`/a/b/c/target/site/thucydides`
plugin writing aggregated report in directory:
`a/b/c/target/site/thucydides`
The report is in wrong directory and it is empty because the plugin is looking in wrong directory for the report.

#### Example 2(no directory specified, using defaults):
current working directory = `a/b/c/`
mvn **-f path/to/module/pom.xml** clean verify site 
serenity runner writes test outcomes to directory:
`/a/b/c/path/to/module/target/site/serenity`
plugin looks for test outcomes in directory:
`/a/b/c/target/site/serenity`
plugin writing aggregated report in directory:
`a/b/c/target/site/serenity`
The report is in wrong directory and it is empty because the plugin is looking in wrong directory for the report.

#### Example 3(specify output directory with serenity prefix)
current working directory = `a/b/c/`
mvn **-f path/to/module/pom.xml** clean verify site -Dserenity.outputDirectory=target/site/thucydides
serenity runner writes test outcomes to directory:
`/a/b/c/path/to/module/target/site/serenity`
plugin looks for test outcomes in directory:
`/a/b/c/target/site/serenity`
plugin writing aggregated report in directory:
`/a/b/c/path/to/module/target/site/serenity`
The report is empty because the plugin is looking in wrong directory for the report.

#### Expected
All 3 directories should be `/a/b/c/path/to/module/target/site/serenity` or `/a/b/c/path/to/module/target/site/thucidides`

#### Workaround:
Specify both serenity.outputDirectory and serenity.sourcesDirectory.
mvn -f path/to/module/pom.xml -Dserenity.outputDirectory=target/site/thucydides -Dserenity.sourceDirectory=target/site/thucydides-
OR
Run maven from the directory the maven module is in:
current working directory = `a/b/c/path/to/module`
mvn clean verify site
All above 3 examples of setting the directories will work and will save the report correctly when running maven this way.

**Comment by TuireHolappa** [comment] 2015-08-19 14:11
After upgrading from Serenity Maven plugin 1.0.47 > 1.1.5 the nice Serenity aggregate reports do not get generated.

Having multimodule Maven project
App
|-bdd
|-etc
Where serenity tests are on the bdd-module.

Running the application level build on Jenkins CI with mvn clean install does not anymore produce the aggregate report like before to App/bdd/target/site/serenity but to App/target/site/serenity. And the problem is that the report is empty.

I tried using some serenity.properties file (bdd/src/main/resources) with items from workaround but that had no effect.
Running the same build cmd on the bdd directory on my own machine does produce the aggregate report correctly.

Any hints how to make aggregate happen on application build?

**Comment by wakaleo** [comment] 2015-08-19 14:54
Could you raise an issue in Github?

On 19 August 2015 at 15:11, TuireHolappa <notifications@github.com> wrote:

> After upgrading from Serenity Maven plugin 1.0.47 > 1.1.5 the nice
> Serenity aggregate reports do not get generated.
>
> Having multimodule Maven project
> App
> |-bdd
> |-etc
> Where serenity tests are on the bdd-module.
>
> Running the application level build on Jenkins CI with mvn clean install
> does not anymore produce the aggregate report like before to
> App/bdd/target/site/serenity but to App/target/site/serenity. And the
> problem is that the report is empty.
>
> I tried using some serenity.properties file (bdd/src/main/resources) with
> items from workaround but that had no effect.
> Running the same build cmd on the bdd directory on my own machine does
> produce the aggregate report correctly.
>
> Any hints how to make aggregate happen on application build?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-maven-plugin/issues/9#issuecomment-132612434>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by TuireHolappa** [comment] 2015-08-19 15:08
I extracted this to https://github.com/serenity-bdd/serenity-maven-plugin/issues/11

**Comment by YamStranger** [comment] 2016-01-29 08:04
Hello @Cristi003 
Thanks for this issue!

Please check it, now it should work fine with serentiy-maven-plugin:1.1.25-rc.3 and serenity-core with serenity-core:1.1.25-rc.3. 
Now, if you will have some project with multi module structure, for example:
App
- bdd
- core
- bdd2

during ``` maven clean verify ``` sererenity.properties from module directory will override properties from project directory (serenity.properties from bdd will override properties in App dir if they are exists), and by default output directory of reports is in module directory, and path provided relative to module directory. 

So after build, by default reports will be under: 
App/
bdd/
     target/serenity/site
core/
     target/serenity/site
bdd2/
     target/serenity/site

Please check this fix, and if all works fine - please close this issue. 

Thanks a lot!!!

**Comment by YamStranger** [comment] 2016-02-08 10:28
It seems that this issue fixed. Will close it

**Closed by YamStranger** 2016-02-08 10:28 UTC
Labels: bug, in progress
