### ISSUE TITLE
Serenity report not getting generated.

### ISSUE THREAD

**Issue by ManasBBSR** [serenity-bdd/serenity-maven-plugin#15] opened 2015-12-01 08:00 UTC
Getting the below error message while trying to execute mvn clean aggregate: I tried using different versions of the serenity-maven-plugin but still getting the same issue.

[INFO] Scanning for projects...
Downloading: http://repo.maven.apache.org/maven2/net/serenity-bdd/maven/plugins/serenity-maven-plugi
n/1.1.17/serenity-maven-plugin-1.1.17.pom
Downloaded: http://repo.maven.apache.org/maven2/net/serenity-bdd/maven/plugins/serenity-maven-plugin
/1.1.17/serenity-maven-plugin-1.1.17.pom (4 KB at 2.7 KB/sec)
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Serenity JUnit Quick Start Project 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- serenity-maven-plugin:1.1.17:aggregate (default-cli) @ Serenity-Demo ---
Merging requirements = [Requirement{name='Search on google', type='feature' parent = 'null', cardNum
ber='null'}]
Merging requirements = []
Merged requirements set = [Requirement{name='Search on google', type='feature' parent = 'null', card
Number='null'}]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.180s
[INFO] Finished at: Tue Dec 01 13:24:53 IST 2015
[INFO] Final Memory: 17M/247M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.1.17:aggregate
 (default-cli) on project Serenity-Demo: Execution default-cli of goal net.serenity-bdd.maven.plugin
s:serenity-maven-plugin:1.1.17:aggregate failed: Couldn't close the zip file: error in opening zip f
ile -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following arti
cles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

Below is the POM File I'm using:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>net.serenity_bdd.samples.junit</groupId>
  <artifactId>Serenity-Demo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>Serenity JUnit Quick Start Project</name>
      <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.1.22-rc.10</serenity.version>
        
        <serenity.maven.version>1.1.17</serenity.maven.version>
        <webdriver.driver>firefox</webdriver.driver>
    </properties>

    <dependencies>
        
        <dependency>
            <groupId>net.serenity-bdd</groupId>     
            <artifactId>serenity-junit</artifactId>
            <version>1.1.22-rc.10</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>     
            <artifactId>serenity-cucumber</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>     
            <artifactId>serenity-core</artifactId>
            <version>1.1.22-rc.10</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.6.1</version>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>1.7.0</version>
            <scope>test</scope>
        </dependency>
      	 <dependency>
	  <groupId>info.cukes</groupId> 
	  <artifactId>cucumber-core</artifactId> 
	  <version>1.2.4</version> 
	  <scope>test</scope> 
	  </dependency>
	 <dependency>
	  <groupId>info.cukes</groupId> 
	  <artifactId>cucumber-java</artifactId> 
	  <version>1.2.2</version> 
	  <scope>test</scope> 
	  </dependency>
	 <dependency>
	  <groupId>info.cukes</groupId> 
	  <artifactId>cucumber-junit</artifactId> 
	  <version>1.2.2</version> 
	  <scope>test</scope> 
	  </dependency>
	 <dependency>
	  <groupId>info.cukes</groupId> 
	  <artifactId>cucumber-jvm-deps</artifactId> 
	  <version>1.0.3</version> 
	  <scope>test</scope> 
	  </dependency> 
	 <dependency>
	  <groupId>info.cukes</groupId> 
	  <artifactId>cucumber-html</artifactId> 
	  <version>0.2.3</version> 
	  <scope>test</scope> 
	  </dependency>	  
	 <dependency>
	  <groupId>info.cukes</groupId> 
	  <artifactId>gherkin</artifactId> 
	  <version>2.12.2</version> 
	  <scope>test</scope> 
	  </dependency>
      <dependency>
	  <groupId>org.seleniumhq.selenium</groupId> 
	  <artifactId>selenium-java</artifactId> 
	  <version>2.45.0</version> 
	  <scope>test</scope> 
	  </dependency> 
	  <dependency>
		<groupId>com.sun.jersey</groupId>
		<artifactId>jersey-client</artifactId>
		<version>1.8</version>
	  </dependency>
	  <dependency>
		<groupId>org.json</groupId>
		<artifactId>json</artifactId>
		<version>20090211</version>
	  </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>                  
                <version>2.18</version>
                <configuration>
                    <includes>
                        <include>**/**Test.java</include>                  
                    </includes>
                    <systemProperties>
                        <webdriver.driver>${webdriver.driver}</webdriver.driver> 
                        <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
                        <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
                    </systemProperties>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>       
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <dependencies>
                     <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>             
                        <goals>
                            <goal>aggregate</goal>                       
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by YamStranger** [comment] 2016-01-17 19:55
Hello @ManasBBSR. 

Thanks for this issue. 

Please add some examples to reproduce this problem - for now I can't do it. 

Thanks!

**Comment by ManasBBSR** [comment] 2016-01-18 07:23
Hi Yaroslav,

Please find attached the sample code where I have used Serenity.

Thanks,
Manas
[Serenity-Demo.zip](https://github.com/serenity-bdd/serenity-maven-plugin/files/93932/Serenity-Demo.zip)

**Comment by YamStranger** [comment] 2016-01-18 07:45
@ManasBBSR Thanks a lot!!!

**Comment by YamStranger** [comment] 2016-02-10 14:17
Hello @ManasBBSR 

Your bug is fixed and will be available in next release of serenity-core and serenty-maven-plugin

Thanks!

**Comment by YamStranger** [comment] 2016-02-20 06:44
It seems that this issue already fixed, will close this issue

**Closed by YamStranger** 2016-02-20 06:44 UTC
Labels: bug, in progress

**Comment by ManasBBSR** [comment] 2016-02-20 11:12
Thanks a lot Yaroslav.

**Comment by Jitendra1665** [comment] 2016-06-10 15:36
Hello , I am also getting the above issue, I would like to know the mistake where I am doing.

The Issue is - 

[INFO] Total time: 13.369 s
[INFO] Finished at: 2016-06-10T21:02:25+05:30
[INFO] Final Memory: 34M/426M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.0.47:aggregate (serenity-reports) on project SprintRunnerBolt: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.0.47:aggregate failed. NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException


Also attached my sample project - I am running the code as - mvn clean verify
[SprintRunnerBolt.zip](https://github.com/serenity-bdd/serenity-maven-plugin/files/309274/SprintRunnerBolt.zip)

**Comment by Jitendra1665** [comment] 2016-06-10 15:37
Can any one please help me..!

**Comment by wakaleo** [comment] 2016-06-10 15:48
First, you should upgrade to the latest version of Serenity. Also, you should 
The attached project isn't running any tests, which is why the report is empty. It is not running the tests because the failsafe plugin is not finding the tests. Once you get the failsafe plugin correctly configured, the reports should be generated correctly.

**Comment by Jitendra1665** [comment] 2016-06-10 16:03
Thanks for your response John, I actually took the latest version of serenity from the maven repository. And the code I took is from the serenity website. I didn't do any more changes other than having some more dependencies..!

I attached the code in the above comment - as a reference if need to check...! please let me know if you need any more information..!

**Comment by wakaleo** [comment] 2016-06-10 16:10
After 1.0.47 the core library was renamed to serenity-core for more consistency. The latest version is on central is 1.1.36 (http://search.maven.org/#search%7Cga%7C1%7Cserenity-core).

**Comment by Jitendra1665** [comment] 2016-06-10 16:20
John, I have done the corresponding changes - still I am getting the same error..! attached the image of the results(no index.html) and also the error message screen shot.

![image](https://cloud.githubusercontent.com/assets/5774988/15970994/25bdd076-2f55-11e6-96cb-7660dac06dcc.png)


I am also attaching the code I tried with.
[SprintRunnerBolt.zip](https://github.com/serenity-bdd/serenity-maven-plugin/files/309365/SprintRunnerBolt.zip)

**Comment by wakaleo** [comment] 2016-06-10 16:21
You need to update your serenity dependency from "core" to "serenity-core".

**Comment by Jitendra1665** [comment] 2016-06-10 16:25
Yes, I have done that is done already - screen shot for the same.
![image](https://cloud.githubusercontent.com/assets/5774988/15971263/eb6899be-2f55-11e6-8457-e44e4cbe617f.png)

**Comment by wakaleo** [comment] 2016-06-10 16:28
The serenity dependency is duplicated in your pom file, make sure there is only one.

**Comment by Jitendra1665** [comment] 2016-06-10 17:06
Thanks a lot for your guidance. My script is running with out fail . but I am not getting pie charts and dependencies is telling like not run..! - Would like to know this time - what could be the reason? Also attached new code. 
[SprintRunnerBolt.zip](https://github.com/serenity-bdd/serenity-maven-plugin/files/309437/SprintRunnerBolt.zip)


![image](https://cloud.githubusercontent.com/assets/5774988/15972337/91b7f792-2f5b-11e6-89f8-18e565ba16ba.png)

**Comment by Jitendra1665** [comment] 2016-06-10 17:17
John, are you able to help me out?

**Comment by Jitendra1665** [comment] 2016-06-10 17:23
I am running the tests as mvn clean verify

**Comment by wakaleo** [comment] 2016-06-10 17:28
The maven-failsafe-plugin is not picking up the tests. You need to ensure that this plugin is configured correctly (see http://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html)

**Comment by Jitendra1665** [comment] 2016-06-10 18:15
I tried figuring out - but not getting any clue..!
I am using as follows : 

this I had taken from Serenity official web site..! http://thucydides.info/docs/serenity-staging/#_building_serenity_projects_in_maven

 <build>
        <plugins>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>                  
                <version>2.18</version>
                <configuration>
                    <includes>
                        <include>**/features/*.java</include>                  
                    </includes>
                    <systemProperties>
                        <webdriver.driver>${webdriver.driver}</webdriver.driver> 
                        <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
                        <surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
                    </systemProperties>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>       
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <dependencies>
                     <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>             
                        <goals>
                            <goal>aggregate</goal>                       
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

**Comment by Jitendra1665** [comment] 2016-06-10 18:18
[SprintRunnerBolt.zip](https://github.com/serenity-bdd/serenity-maven-plugin/files/309529/SprintRunnerBolt.zip) - code is as follows

**Comment by Jitendra1665** [comment] 2016-06-10 18:20
not getting any clue where I am doing mistake..!

**Comment by wakaleo** [comment] 2016-06-10 18:22
Try starting from scratch using the Serenity Maven archetype.

**Comment by Jitendra1665** [comment] 2016-06-10 18:23
ok

**Comment by Jitendra1665** [comment] 2016-06-10 19:07
tried , still getting same issue..!

**Comment by wakaleo** [comment] 2016-06-10 19:39
Make sure you update the serenity version. Are any tests running?

**Comment by Jitendra1665** [comment] 2016-06-10 19:46
No - No tests are running in serenity? all the places I updated version currectly..!

**Comment by Jitendra1665** [comment] 2016-06-10 19:52
Reports are not having any pie charts becasue all tests are not running..!

**Comment by Jitendra1665** [comment] 2016-06-10 19:52
But ever time build is getting sucess

**Comment by wakaleo** [comment] 2016-06-10 19:56
That would be a maven (fail safe) configuration issue. Try removing the failsafe inclusions configuration and renaming your test classes so that they end in "Test"

**Comment by Jitendra1665** [comment] 2016-06-10 20:10
I will try it tomorrow and let you know..! Thanks for your response...! I tried changing to test but not yet worked..!

**Comment by jogjitu** [comment] 2016-09-03 11:36
@wakaleo I am running serenity-cucumber project and get blank results

**Comment by wakaleo** [comment] 2016-09-03 11:39
If none of the tests are running at all, it is generally a Maven/Surefire configuration issue of some kind.

**Comment by jogjitu** [comment] 2016-09-03 11:50
I am using gradle tests are running fine just the reports are blank

**Comment by wakaleo** [comment] 2016-09-03 11:52
Can you provide a sample project that reproduces the problem?

**Comment by jogjitu** [comment] 2016-09-03 12:07
[automate-tests.zip](https://github.com/serenity-bdd/serenity-maven-plugin/files/453357/pathship-automate-tests.zip)

**Comment by cliviu** [comment] 2016-09-09 21:34
hi @jogjitu , Thanks for uploading the project, I will take a look at your problem

**Comment by cliviu** [comment] 2016-09-09 21:56
when running your project, I've noticed a problem with the gradle build regarding the xml-apis libraries. 
[build.gradle.zip](https://github.com/serenity-bdd/serenity-maven-plugin/files/464911/build.gradle.zip)
Please try again with the attached build.gradle, let me know if it works

**Comment by siva90144** [comment] 2017-02-20 20:08
I am also getting index.html as blank. it is not showing any pie chart. but i am getting individual report and  test case is executing
![report](https://cloud.githubusercontent.com/assets/19613704/23140244/12f730ec-f776-11e6-96d5-3d38060f76c4.png)

**Comment by wakaleo** [comment] 2017-02-20 20:25
See https://github.com/serenity-bdd/serenity-core/issues/692
